"""initall

Revision ID: 22331b67f1e8
Revises: 
Create Date: 2025-06-10 16:23:02.384727

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '22331b67f1e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_types',
                    sa.Column('id', sa.Integer(), nullable=False, comment='PK — уникальный идентификатор типа сырья'),
                    sa.Column('name', sa.String(length=100), nullable=False, comment='Название типа сырья'),
                    sa.Column('loss_percent', sa.Float(), nullable=False,
                              comment='Процент потери сырья при производстве'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    comment='Справочник типов сырья: содержит процент потерь сырья'
                    )
    op.create_table('product_types',
                    sa.Column('id', sa.Integer(), nullable=False,
                              comment='PK — уникальный идентификатор типа продукции'),
                    sa.Column('name', sa.String(length=100), nullable=False, comment='Название типа продукции'),
                    sa.Column('coefficient', sa.Float(), nullable=False,
                              comment='Коэффициент типа продукции для расчёта расхода сырья'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    comment='Справочник типов продукции: коэффициент расхода сырья'
                    )
    op.create_table('suppliers',
                    sa.Column('id', sa.Integer(), nullable=False, comment='PK — уникальный идентификатор поставщика'),
                    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование поставщика'),
                    sa.Column('inn', sa.String(length=12), nullable=False, comment='ИНН поставщика'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('inn'),
                    comment='Справочник поставщиков сырья'
                    )
    op.create_table('units',
                    sa.Column('id', sa.Integer(), nullable=False,
                              comment='PK — уникальный идентификатор единицы измерения'),
                    sa.Column('name', sa.String(length=50), nullable=False, comment='Название единицы измерения'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    comment='Справочник единиц измерения материалов'
                    )
    op.create_table('materials',
                    sa.Column('id', sa.Integer(), nullable=False, comment='PK — уникальный идентификатор материала'),
                    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование материала'),
                    sa.Column('description', sa.String(), nullable=True, comment='Описание материала'),
                    sa.Column('image_path', sa.String(), nullable=True, comment='Путь к изображению материала'),
                    sa.Column('material_type_id', sa.Integer(), nullable=False, comment='FK → material_types.id'),
                    sa.Column('unit_id', sa.Integer(), nullable=False, comment='FK → units.id'),
                    sa.Column('quantity', sa.Integer(), nullable=False, comment='Текущее количество на складе'),
                    sa.Column('min_quantity', sa.Integer(), nullable=False, comment='Минимально допустимое количество'),
                    sa.Column('pack_size', sa.Integer(), nullable=False, comment='Количество единиц в одной упаковке'),
                    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False,
                              comment='Цена за единицу материала'),
                    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
                    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Материалы на складе: основной справочник'
                    )
    op.create_table('material_suppliers',
                    sa.Column('material_id', sa.Integer(), nullable=False, comment='PK часть — материал'),
                    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='PK часть — поставщик'),
                    sa.Column('rating', sa.Float(), nullable=False, comment='Рейтинг качества поставки материала'),
                    sa.Column('start_date', sa.Date(), nullable=False,
                              comment='Дата начала сотрудничества с поставщиком по данному материалу'),
                    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('material_id', 'supplier_id'),
                    comment='Рейтинг и дата начала работы поставщика по конкретному материалу'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_suppliers')
    op.drop_table('materials')
    op.drop_table('units')
    op.drop_table('suppliers')
    op.drop_table('product_types')
    op.drop_table('material_types')
    # ### end Alembic commands ###
